//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.impl;

import static org.junit.Assert.*;

import java.util.UUID;

import com.hp.api.NotFoundException;

import com.fct.nat.model.NAT;
import com.fct.nat.api.NATService;

import com.hp.api.Id;

import org.junit.Before;
import org.junit.Test;

/**
 * Sample test of the NAT service implementation.
 */
public class NATManagerTest {
  /*
    private NATService svc;

    @Before
    public void setUp() {
        svc = new NATManager();
    }
  
    @Test
    public void basics() {
        NAT s = svc.create("Gizmo");
        assertNotNull("incorrect create", s.getId());
        assertEquals("incorrect get", s, svc.get(s.getId()));
        assertEquals("incorrect name", "Gizmo", s.name());
        svc.delete(s.getId());
        try{
            svc.get(s.getId());
            fail("Expected exception");
        } catch(NotFoundException e) {
            
        }
    }

    @Test
    public void defaults() {
        NAT s = svc.create(null);
        assertNotNull("incorrect id", s.getId());
        assertNotNull("incorrect name", s.name());
    }

    @Test(expected=NotFoundException.class)
    public void notFound() {
        Id<NAT, UUID> id = Id.valueOf(UUID.randomUUID());
        svc.get(id);
    }*/
}
