//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.api.Transportable;
import com.hp.sdn.BaseModel;
import com.hp.sdn.auditlog.AuditLogEntry;
import com.hp.sdn.Model;

/**
 * Sample NAT domain model.
 */
public class NAT extends Model<NAT> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public NAT() {
        super();
    }

    /** 
     * Creates a new NAT entity. 
     *
     * @param name NAT name
     */
    public NAT(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new NAT entity. 
     *
     * @param id NAT unique id
     * @param name NAT name
     */
    public NAT(Id<NAT, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the NAT name.
     *
     * @return NAT name
     */
    public String name() {
        return name;
    }

    /**
     * Set the NAT name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
