//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.model;

/**
 * NAT sort attribute.
 */
public enum NATSortAttribute {

    /** Sorts by name */
    //NAME

}
