//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.firewall.model;

/**
 * Firewall sort attribute.
 */
public enum FirewallSortAttribute {

    /** Sorts by name */
    NAME

}
