//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.rs;

import static org.easymock.EasyMock.createMock;
import static org.easymock.EasyMock.expect;
import static org.easymock.EasyMock.replay;
import static org.easymock.EasyMock.verify;

import java.util.UUID;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;

import javax.ws.rs.core.MediaType;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.hp.util.rs.ResourceTest;
import com.hp.sdn.rs.misc.ControllerResourceTest;

import com.fct.nat.model.NAT;
import com.fct.nat.api.NATService;

import com.hp.api.Id;


/**
 * Sample NAT REST API resource.
 */
public class NATResourceTest extends ControllerResourceTest {

    private NATService svc;
    
    /**
     * Creates a test suite on the default package set.
     */
    public NATResourceTest() {
        super("com.fct.nat.rs");
    }
    

    @Override
    @Before
    public void setUp() throws Exception {
        super.setUp();
        svc = createMock(NATService.class);

        sl.register(NATService.class, svc,
                    Collections.<String, Object> emptyMap());

        // If a specific test case expects a different format, such
        // format will have to be set calling this method.
        ResourceTest.setDefaultMediaType(MediaType.APPLICATION_JSON);
    }
    
    @Override
    @After
    public void tearDown() throws Exception {
        super.tearDown();
        sl.unregister(NATService.class, svc);
    }   

    /*@Test
    public void addNAT() {
        NAT s = new NAT("Thingie");
        
        expect(svc.create("Thingie"))
            .andReturn(s);
        replay(svc);
        
        String r = post("NAT",  
                        "{\"item\":{\"name\":\"Thingie\"}}");
        assertResponseContains(r, "\"uid\":\"" + s.getId().getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getNAT() {
        Id<NAT, UUID> id = Id.valueOf(UUID.randomUUID());
        
        expect(svc.get(id)).andReturn(new NAT(id, "Thingie"));
        replay(svc);
        
        String r = get("NAT/" + id.getValue());
        assertResponseContains(r, "\"uid\":\"" + id.getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getAll() {
        Id<NAT, UUID> id1 = Id.valueOf(UUID.randomUUID());
        Id<NAT, UUID> id2 = Id.valueOf(UUID.randomUUID());

        Collection<NAT> c = new HashSet<NAT>();
        c.add(new NAT(id1, "Thingie"));
        c.add(new NAT(id2, "Doo-Hickey"));
        expect(svc.getAll()).andReturn(c);
        replay(svc);

        String r = get("NAT");
        assertResponseContains(r, "\"NAT\":[",
                               "{\"uid\":\"" + id1.getValue() + "\"", "{\"uid\":\"" + id2.getValue() + "\"");
        verify(svc);
    }

    @Test
    public void deleteNAT() {
        Id<NAT, UUID> id = Id.valueOf(UUID.randomUUID());
        
        svc.delete(id);
        replay(svc);
        
        String r = delete("NAT/" + id.getValue());
        verify(svc);
    }*/
}
