//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.api;

import java.util.UUID;

import com.fct.nat.model.NAT;
import com.hp.api.NotFoundException;

import com.hp.api.Id;

import java.util.Collection;

/**
 * Sample NAT service interface.
 */
public interface NATService {

    /**
     * Get all NAT items.
     *
     * @return collection of all NAT items
     */
    //public Collection<NAT> getAll();

    /** 
     * Creates a new NAT entity.
     *
     * @param id unique id to be assigned to the new NAT entity.
     * @param name NAT name
     * @return newly created NAT
     */
    //public NAT create(String name);

    /**
     * Get the NAT with the specified unique id.
     *
     * @param uid unique id of the NAT entity to be retrieved
     * @return NAT with the given unique id
     * @throws NotFoundException if the requested NAT was not found
     */
    //public NAT get(Id<NAT, UUID> id);

    /**
     * Delete the NAT with the specified id.
     *
     * @param uid unique id of the NAT entity to be deleted
     * @return deleted NAT
     * @throws NotFoundException if the requested NAT was not found
     */
    // public void delete(Id<NAT, UUID> id);

}
