//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.nat.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the NAT domain model.
 */
public class NATTest {

    @Test
    public void basic() {
        Id<NAT, UUID> id = Id.valueOf(UUID.randomUUID());
        NAT s = new NAT(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
