//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.firewall.ui;

import org.apache.felix.scr.annotations.Component;

import com.hp.sdn.ui.misc.SelfRegisteringUIExtension;

/**
 * Firewall UI extension, which provides additional UI elements to the
 * HP SDN Controller GUI.
 */
@Component
public class UIExtension extends SelfRegisteringUIExtension {
    
    /** Create the core UI elements contributor. */
    public UIExtension() {
        super("firewall", "com/fct/firewall/ui", UIExtension.class);
    }

}
