//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.firewall.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the Firewall domain model.
 */
public class FirewallTest {

    @Test
    public void basic() {
        Id<Firewall, UUID> id = Id.valueOf(UUID.randomUUID());
        Firewall s = new Firewall(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
